import { AdminUser } from "./admin-service";

// Demo data for testing the admin dashboard
export const demoAdminUsers: AdminUser[] = [
  // Startups
  {
    id: "1",
    name: "John Smith",
    email: "john@ecosolutions.com",
    phone: "+1-555-0123",
    type: "startup",
    verified: true,
    status: "approved",
    visibility_status: "featured",
    admin_notes: "Innovative cleantech startup with strong potential",
    verified_at: "2024-01-15T10:00:00Z",
    verified_by: "admin123",
    created_at: "2024-01-10T09:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah@meditech.io",
    phone: "+1-555-0456",
    type: "startup",
    verified: false,
    status: "pending",
    admin_notes: "Pending review for medical device startup",
    created_at: "2024-01-20T14:30:00Z",
  },
  {
    id: "3",
    name: "Mike Chen",
    email: "mike@financeai.com",
    phone: "+1-555-0789",
    type: "startup",
    verified: false,
    status: "flagged",
    admin_notes: "Requires additional documentation",
    created_at: "2024-01-18T11:15:00Z",
  },
  {
    id: "4",
    name: "Emma Davis",
    email: "emma@foodtech.co",
    phone: "+1-555-0321",
    type: "startup",
    verified: false,
    status: "rejected",
    admin_notes: "Incomplete business plan and lack of team experience",
    created_at: "2024-01-12T16:45:00Z",
  },
  // Investors
  {
    id: "5",
    name: "Robert Wilson",
    email: "robert@vcfund.com",
    phone: "+1-555-1234",
    type: "investor",
    verified: true,
    status: "approved",
    visibility_status: "hot",
    admin_notes: "Experienced VC with strong track record",
    verified_at: "2024-01-14T08:00:00Z",
    verified_by: "admin123",
    created_at: "2024-01-08T10:00:00Z",
    updated_at: "2024-01-14T08:00:00Z",
  },
  {
    id: "6",
    name: "Lisa Anderson",
    email: "lisa@angelgroup.org",
    phone: "+1-555-5678",
    type: "investor",
    verified: false,
    status: "pending",
    admin_notes: "Angel investor application under review",
    created_at: "2024-01-22T13:20:00Z",
  },
  {
    id: "7",
    name: "David Brown",
    email: "david@privateequity.com",
    phone: "+1-555-9012",
    type: "investor",
    verified: true,
    status: "approved",
    admin_notes: "Verified private equity investor",
    verified_at: "2024-01-16T15:30:00Z",
    verified_by: "admin123",
    created_at: "2024-01-11T12:00:00Z",
    updated_at: "2024-01-16T15:30:00Z",
  },
  {
    id: "8",
    name: "Jennifer Lee",
    email: "jen@cryptofund.io",
    phone: "+1-555-3456",
    type: "investor",
    verified: false,
    status: "flagged",
    admin_notes: "Suspicious activity detected, under investigation",
    created_at: "2024-01-19T09:45:00Z",
  },
];

// Mock dashboard stats
export const demoDashboardStats = {
  totalStartups: 4,
  totalInvestors: 4,
  pendingApprovals: 2,
  approvedUsers: 4,
  rejectedUsers: 1,
  flaggedUsers: 2,
};

// Demo detailed startup data
export const demoStartupDetails = {
  "1": {
    id: "1",
    name: "John Smith",
    email: "john@ecosolutions.com",
    phone: "+1-555-0123",
    startup_name: "EcoSolutions",
    website: "https://ecosolutions.com",
    industry: "CleanTech",
    stage: "MVP",
    problem_solving:
      "Developing sustainable waste management solutions for urban environments",
    solution: "AI-powered waste sorting and recycling optimization platform",
    uniqueness:
      "First-to-market AI solution with 95% accuracy in waste classification",
    capital_seeking: 2000000,
    pre_money_valuation: 8000000,
    current_financial_year_revenue: 150000,
    monthly_burn_rate: 50000,
    created_at: "2024-01-10T09:00:00Z",
  },
  "2": {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah@meditech.io",
    phone: "+1-555-0456",
    startup_name: "MediTech Solutions",
    website: "https://meditech.io",
    industry: "HealthTech",
    stage: "Idea",
    problem_solving:
      "Improving patient monitoring in remote healthcare settings",
    solution: "Wearable devices with real-time health monitoring and alerts",
    uniqueness: "Advanced biosensor technology with FDA-approved components",
    capital_seeking: 1500000,
    pre_money_valuation: 5000000,
    current_financial_year_revenue: 0,
    monthly_burn_rate: 25000,
    created_at: "2024-01-20T14:30:00Z",
  },
};

// Demo detailed investor data
export const demoInvestorDetails = {
  "5": {
    id: "5",
    name: "Robert Wilson",
    email: "robert@vcfund.com",
    phone: "+1-555-1234",
    company: "Wilson Venture Capital",
    role: "Managing Partner",
    city: "San Francisco",
    country: "United States",
    linkedin_profile: "https://linkedin.com/in/robertwilson",
    average_ticket_size: "$500K - $2M",
    number_of_investments: 25,
    preferred_industries: "FinTech, CleanTech, HealthTech",
    preferred_company_stage: "Series A",
    created_at: "2024-01-08T10:00:00Z",
  },
  "6": {
    id: "6",
    name: "Lisa Anderson",
    email: "lisa@angelgroup.org",
    phone: "+1-555-5678",
    company: "Bay Area Angels",
    role: "Investment Committee Member",
    city: "Palo Alto",
    country: "United States",
    linkedin_profile: "https://linkedin.com/in/lisaanderson",
    average_ticket_size: "$25K - $100K",
    number_of_investments: 12,
    preferred_industries: "SaaS, E-commerce",
    preferred_company_stage: "Seed",
    created_at: "2024-01-22T13:20:00Z",
  },
};
