
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqnfbyptnlgnlrvanber.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbmZieXB0bmxnbmxydmFuYmVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTc2NzksImV4cCI6MjA1NzY5MzY3OX0.dMBSankzTOsACXMzBsGMaE3DCgvOlr775hMfusFBLEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-client',
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 5
    }
  }
});
